# Python CircleCI 2.0 configuration file

version: 2
jobs:
  build_36:
    docker:
      - image: circleci/python:3.6

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-python36-dependencies-{{ checksum "requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-python36-dependencies-

    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade setuptools
          pip install flake8
          pip install -r requirements.txt
          pip install -r requirements-gatherers.txt
          pip install -r requirements-scanners.txt
          pip install -r requirements-dev.txt

    - save_cache:
        paths:
          - ./venv
        key: v1-python36-dependencies-{{ checksum "requirements.txt" }}

    - run:
        name: run tests
        command: |
          . venv/bin/activate
          ./test.sh

    - store_artifacts:
        path: test-reports
        destination: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_36
