selectusa.gov:
  redirect: https://www.selectusa.gov/welcome
  blacklist: false
flightschoolcandidates.gov:
  redirect: https://www.flightschoolcandidates.gov/afsp2/?acct_type=c&section=wn
  blacklist: false
onhir.gov:
  redirect: https://www.doi.gov/
  blacklist: false
banknet.gov:
  redirect: https://www.banknet.gov/entrance/default.html
  blacklist: false
broadband.gov:
  redirect: https://www.fcc.gov/general/national-broadband-plan
  blacklist: false
privacyshield.gov:
  redirect: https://www.privacyshield.gov/welcome
  blacklist: false
nationalhousinglocator.gov:
  redirect: https://portal.hud.gov/hudportal/hud
  blacklist: true
disasterhousing.gov:
  redirect: https://portal.hud.gov/hudportal/hud
  blacklist: true
nls.gov:
  redirect: https://portal.hud.gov/hudportal/hud
  blacklist: true
nationalhousing.gov:
  redirect: https://portal.hud.gov/hudportal/hud
  blacklist: true
nationalbanknet.gov:
  redirect: https://www.banknet.gov/entrance/default.html
  blacklist: false
dea.gov:
  redirect: https://www.dea.gov/index.shtml
  blacklist: false
ourdocuments.gov:
  redirect: https://www.ourdocuments.gov/index.php?flash=false&
  blacklist: false
nmcourt.fed.us:
  redirect: http://nmcourt.fed.us/web/index.htm
  blacklist: false
